<ShowActionBar>:
    orientation: "vertical"
    ActionBar:
        ActionView:
            use_seperator: True
            ActionPrevious:
                title: "My Title"
                with_previous: False
            ActionOverflow:
                ActionButton:
                    text: "Settings"
            ActionButton:
                text: "Log Out"
    Label:
        text: 'the next widget added fills all the extra space'
        text_size: self.size
        halign: 'center'
        valign: 'middle'
