## A complete definition of our UI using a root rule.
RootObj:
	cols: 4
	padding: 10, 10, 20, 10
	background_color: (.3, .3, .3, 1)

	MyButton:
		text: "one"
		background_color: (1, 0, 0, 1)
		size: 200, 200
	MyButton:
		text: "two"
		background_color: (1, 0, 0, 1)
		size: 200, 200
	MyButton:
		text: "three"
		background_color: (1, 0, 0, 1)
		size: 200, 200
	MyLabel:
		text: "label - four"
		background_color: (1, 0, 0, 1)
		size: 200, 200
