WebColours = {	"Indian Red": ('CD5C5CFF'),
					"Light Coral": ('F08080FF'),
					"Salmon": ('FA8072FF'),
					"Dark Salmon": ('E9967AFF'),
					"Light Salmon": ('FFA07AFF'),
					"Crimson": ('DC143CFF'),
					"Red": ('FF0000FF'),
					"Fire Brick": ('B22222FF'),
					"Dark Red": ('8B0000FF'),
					"Pink": ('FFC0CBFF'),
					"Light Pink": ('FFB6C1FF'),
					"Hot Pink": ('FF69B4FF'),
					"Deep Pink": ('FF1493FF'),
					"Medium Violet Red": ('C71585FF'),
					"Pale Violet Red": ('DB7093FF'),
					"Light Salmon": ('FFA07AFF'),
					"Coral": ('FF7F50FF'),
					"Tomato": ('FF6347FF'),
					"Orange Red": ('FF4500FF'),
					"Dark Orange": ('FF8C00FF'),
					"Orange": ('FFA500FF'),
					"Gold": ('FFD700FF'),
					"Yellow": ('FFFF00FF'),
					"Light Yellow": ('FFFFE0FF'),
					"Lemon Chiffon": ('FFFACDFF'),
					"Light Goldenrod Yellow": ('FAFAD2FF'),
					"Papaya Whip": ('FFEFD5FF'),
					"Moccasin": ('FFE4B5FF'),
					"Peach Puff": ('FFDAB9FF'),
					"Pale Goldenrod": ('EEE8AAFF'),
					"Khaki": ('F0E68CFF'),
					"Dark Khaki": ('BDB76BFF'),
					"Lavender": ('E6E6FAFF'),
					"Thistle": ('D8BFD8FF'),
					"Plum": ('DDA0DDFF'),
					"Violet": ('EE82EEFF'),
					"Orchid": ('DA70D6FF'),
					"Fuchsia": ('FF00FFFF'),
					"Magenta": ('FF00FFFF'),
					"Medium Orchid": ('BA55D3FF'),
					"Medium Purple": ('9370DBFF'),
					"Rebecca Purple": ('663399FF'),
					"Blue Violet": ('8A2BE2FF'),
					"Dark Violet": ('9400D3FF'),
					"Dark Orchid": ('9932CCFF'),
					"Dark Magenta": ('8B008BFF'),
					"Purple": ('800080FF'),
					"Indigo": ('4B0082FF'),
					"Slate Blue": ('6A5ACDFF'),
					"Dark Slate Blue": ('483D8BFF'),
					"Medium Slate Blue": ('7B68EEFF'),
					"Green Yellow": ('ADFF2FFF'),
					"Chartreuse": ('7FFF00FF'),
					"Lawn Green": ('7CFC00FF'),
					"Lime": ('00FF00FF'),
					"Lime Green": ('32CD32FF'),
					"Pale Green": ('98FB98FF'),
					"Light Green": ('90EE90FF'),
					"Medium Spring Green": ('00FA9AFF'),
					"Spring Green": ('00FF7FFF'),
					"Medium Sea Green": ('3CB371FF'),
					"Sea Green": ('2E8B57FF'),
					"Forest Green": ('228B22FF'),
					"Green": ('008000FF'),
					"Dark Green": ('006400FF'),
					"Yellow Green": ('9ACD32FF'),
					"Olive Drab": ('6B8E23FF'),
					"Olive": ('808000FF'),
					"Dark Olive Green": ('556B2FFF'),
					"Medium Aquamarine": ('66CDAAFF'),
					"Dark Sea Green": ('8FBC8BFF'),
					"Light Sea Green": ('20B2AAFF'),
					"Dark Cyan": ('008B8BFF'),
					"Teal": ('008080FF'),
					"Aqua": ('00FFFFFF'),
					"Cyan": ('00FFFFFF'),
					"Light Cyan": ('E0FFFFFF'),
					"Pale Turquoise": ('AFEEEEFF'),
					"Aquamarine": ('7FFFD4FF'),
					"Turquoise": ('40E0D0FF'),
					"Medium Turquoise": ('48D1CCFF'),
					"Dark Turquoise": ('00CED1FF'),
					"Cadet Blue": ('5F9EA0FF'),
					"Steel Blue": ('4682B4FF'),
					"Light Steel Blue": ('B0C4DEFF'),
					"Powder Blue": ('B0E0E6FF'),
					"Light Blue": ('ADD8E6FF'),
					"Sky Blue": ('87CEEBFF'),
					"Light Sky Blue": ('87CEFAFF'),
					"Deep Sky Blue": ('00BFFFFF'),
					"Dodger Blue": ('1E90FFFF'),
					"Cornflower Blue": ('6495EDFF'),
					"Medium Slate Blue": ('7B68EEFF'),
					"Royal Blue": ('4169E1FF'),
					"Blue": ('0000FFFF'),
					"Medium Blue": ('0000CDFF'),
					"Dark Blue": ('00008BFF'),
					"Navy": ('000080FF'),
					"Midnight Blue": ('191970FF'),
					"Cornsilk": ('FFF8DCFF'),
					"Blanched Almond": ('FFEBCDFF'),
					"Bisque": ('FFE4C4FF'),
					"Navajo White": ('FFDEADFF'),
					"Wheat": ('F5DEB3FF'),
					"Burly Wood": ('DEB887FF'),
					"Tan": ('D2B48CFF'),
					"Rosy Brown": ('BC8F8FFF'),
					"Sandy Brown": ('F4A460FF'),
					"Goldenrod": ('DAA520FF'),
					"Dark Goldenrod": ('B8860BFF'),
					"Peru": ('CD853FFF'),
					"Chocolate": ('D2691EFF'),
					"Saddle Brown": ('8B4513FF'),
					"Sienna": ('A0522DFF'),
					"Brown": ('A52A2AFF'),
					"Maroon": ('800000FF'),
					"White": ('FFFFFFFF'),
					"Snow": ('FFFAFAFF'),
					"Honey Dew": ('F0FFF0FF'),
					"Mint Cream": ('F5FFFAFF'),
					"Azure": ('F0FFFFFF'),
					"Alice Blue": ('F0F8FFFF'),
					"Ghost White": ('F8F8FFFF'),
					"White Smoke": ('F5F5F5FF'),
					"Sea Shell": ('FFF5EEFF'),
					"Beige": ('F5F5DCFF'),
					"Old Lace": ('FDF5E6FF'),
					"Floral White": ('FFFAF0FF'),
					"Ivory": ('FFFFF0FF'),
					"Antique White": ('FAEBD7FF'),
					"Linen": ('FAF0E6FF'),
					"Lavender Blush": ('FFF0F5FF'),
					"Misty Rose": ('FFE4E1FF'),
					"Gainsboro": ('DCDCDCFF'),
					"Light Gray": ('D3D3D3FF'),
					"Silver": ('C0C0C0FF'),
					"Dark Gray": ('A9A9A9FF'),
					"Gray": ('808080FF'),
					"Dim Gray": ('696969FF'),
					"Light Slate Gray": ('778899FF'),
					"Slate Gray": ('708090FF'),
					"Dark Slate Gray": ('2F4F4FFF'),
					"Black": ('000000FF')
					}

def get_colour(colour):
	print("colour: ", colour)
	print("result: ", WebColours[colour])
	return WebColours[colour]

def nailed_colour():
	return '#CD5C5C'